### ISSUE TITLE
A malicious user could change the title of a shop

### ISSUE THREAD

**Issue by sofar** [SmallJoker/bitchange#11]
https://github.com/SmallJoker/bitchange/blob/3f029c82d6fc5ac8c73657384168817356be72e6/shop.lua#L204

It is never verified that the player has permission to modify the title field, and the code accepts any client data where `fields.title` is set, allowing a player to deface the shop title.

**Comment by SmallJoker** [comment]
Good catch. Thanks for pointing this out.
